version: '3.2'

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.7.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.7.0
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2.0-alpine
    ports:
      - "6379:6379"

  authapi:
    build:
      context: auth/
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD
    ports:
    - "5000:5000"
    depends_on:
      - postgres
      - redis

  etl:
    build:
      context: postgres_to_es/
    environment:
      - POSTGRES_HOST #=postgres # здесь можно было взять переменные окружения с хоста,
      - POSTGRES_DB #=movies # чтобы подключение было удобнее и безопаснее
      - POSTGRES_USER #=postgres # но для показательного запуска оставил дефолтное подключение к db
      - POSTGRES_PORT #=5432 # у меня свои настройки на Heroku
      - POSTGRES_PASSWORD #=postgres
      - ELASTIC_HOST #=elasticsearch
      - ELASTIC_PORT #=9200
      - ELASTIC_USER #не заполняется, так как у меня trial без пароля
      - ELASTIC_PASSWORD
      - ELASTIC_INDEX=movies
      - REDIS_HOST=redis # поставил подключение к версии из compose.
      - REDIS_PORT=6379 # но у меня личный на Heroku
      - REDIS_PASSWORD
    depends_on:
      - elasticsearch
      - redis

  asyncapi:
    build:
      context: asyncapi/
    environment:
      - ELASTIC_HOST #=elasticsearch
      - ELASTIC_PORT #=9200
      - ELASTIC_USER #не заполняется, так как у меня trial без пароля
      - ELASTIC_PASSWORD
      - ELASTIC_INDEX=movies
      - REDIS_HOST=redis # поставил подключение к версии из compose.
      - REDIS_PORT=6379 # но у меня личный на Heroku
      - REDIS_PASSWORD
      - JWT_KEY_URL="authapi:5000/public_key"
    ports:
    - "8000:8000"
    depends_on:
      - elasticsearch
      - redis
      - auth

volumes:
  elasticsearch:
